# Используем официальный образ Python
FROM python:3.10

# Копируем все файлы в рабочую директорию в контейнере
COPY . /app

# Устанавливаем зависимости
WORKDIR /app
RUN pip install -r requirements.txt

# Запускаем скрипт codegen.py
CMD ["python", "codegen.py"]

# Открываем порт 8001 для контейнера
EXPOSE 8001
